### ISSUE TITLE
How to manage secrets in K8s

### ISSUE THREAD

**Issue by zmoog** [zmoog/go-bender#5]
Bender needs some secrets. For example, today, it only requires the `DISCORD_TOKEN` environment variable.

However, we'll probably add more environment variables shortly. Using environment variables from a terminal is fine, but when we run Bender in K8s, we need a way to properly handle secrets like the Discord token other than writing them plaintext in .yaml files.

IIRC, K8s has a built-in mechanism to handle secrets. Find a simple and effective way to handle secrets so we can keep this repo free from application secrets.

**Comment by zmoog** [comment]
Reading https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by zmoog** [comment]
> A Secret is an object that contains a small amount of sensitive data such as a password, a token, or a key. Such information might otherwise be put in a [Pod](https://kubernetes.io/docs/concepts/workloads/pods/) specification or in a [container image](https://kubernetes.io/docs/reference/glossary/?all=true#term-image). Using a Secret means that you don't need to include confidential data in your application code.

> Secrets are similar to [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/) but are specifically intended to hold confidential data.


Kind
https://github.com/kubernetes-sigs/kind

From https://github.com/kubernetes-sigs/kind/releases, I am using:

```text
kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
```

Reading the following to understand how to create secrets.

- https://kubernetes.io/docs/concepts/configuration/secret/
- https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data


Weird, I don't have kubectl installed on the NUC.

```shell
brew install kubectl
```

```shell
$ create secret generic discord-token --from-literal=discord-token='[secret]'
secret/discord-token created
```

So we can access the secret with:

```shell
$ kubectl get secret discord-token
NAME            TYPE     DATA   AGE
discord-token   Opaque   1      98s

$ kubectl delete secret discord-token
secret "discord-token" deleted
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend-username
```

So, for Bender, we can access the secret with:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          name: discord-token
          key: discord-token
```
